In [1]:
#@title connect drive and basic setup

import os
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import keras 
import math

from google.colab import drive
drive.mount('/content/gdrive')
%cd 'gdrive/MyDrive/Colab Notebooks/pruning'

Mounted at /content/gdrive
/content/gdrive/MyDrive/Colab Notebooks/pruning


In [2]:
%load_ext autoreload
%autoreload 2

# pruning random features model - Gaussian input

## single output

In [ ]:
from utils_tf import (make_2layer_net, train_teacher_student_gaussian_input,
                      kernel_of_nn)
N1 = 1000
N2 = 1
d = 500
M = 5
num_iter = 2000
bsize = 5000

target_model = make_2layer_net(d, N1, N2)
pruned_model = make_2layer_net(d, M, N2)
optimizer = tf.keras.optimizers.Adam()
train_teacher_student_gaussian_input(pruned_model, target_model, num_iter, bsize, optimizer)

Training loss at step 0: 132.9955
Training loss at step 200: 48.2111
Training loss at step 400: 19.9630
Training loss at step 600: 18.7436
Training loss at step 800: 18.9122
Training loss at step 1000: 19.1151
Training loss at step 1200: 18.9490
Training loss at step 1400: 18.9050
Training loss at step 1600: 19.0165
Training loss at step 1800: 19.3515


In [ ]:
print(np.round(kernel_of_nn(pruned_model), 3))

[[ 1.    -0.252 -0.25  -0.247 -0.249]
 [-0.252  1.    -0.247 -0.251 -0.249]
 [-0.25  -0.247  1.    -0.25  -0.247]
 [-0.247 -0.251 -0.25   1.    -0.25 ]
 [-0.249 -0.249 -0.247 -0.25   1.   ]]


## multiple outputs

In [ ]:
from utils_tf import (make_2layer_net, train_teacher_student_gaussian_input,
                      kernel_of_nn)
N1 = 1000
N2 = 4
d = 500
M = 5
num_iter = 2000
bsize = 5000

target_model = make_2layer_net(d, N1, N2)
pruned_model = make_2layer_net(d, M, N2)
optimizer = tf.keras.optimizers.Adam()
train_teacher_student_gaussian_input(pruned_model, target_model, num_iter, bsize, optimizer)

Training loss at step 0: 135.1566
Training loss at step 200: 48.4892
Training loss at step 400: 22.4878
Training loss at step 600: 19.8761
Training loss at step 800: 19.6192
Training loss at step 1000: 19.8047
Training loss at step 1200: 19.2186
Training loss at step 1400: 19.5110
Training loss at step 1600: 19.3849
Training loss at step 1800: 19.0423


In [ ]:
print(np.round(kernel_of_nn(pruned_model), 3))

[[ 1.    -0.25  -0.253 -0.248 -0.249]
 [-0.25   1.    -0.251 -0.252 -0.247]
 [-0.253 -0.251  1.    -0.247 -0.247]
 [-0.248 -0.252 -0.247  1.    -0.249]
 [-0.249 -0.247 -0.247 -0.249  1.   ]]


## multi-layer neural nets

In [6]:
from utils_tf import neural_net, kernel_of_nn, train_teacher_student_gaussian_input

target_model = neural_net(100, [1000], 2)

In [11]:
d = 500
Ns = [1000, 1000]
Ms = [5, 5]
out_dim = 1
num_iter = 3000
bsize = 1000

target_model = neural_net(d, Ns, out_dim)
pruned_model = neural_net(d, Ms, out_dim)
optimizer = tf.keras.optimizers.Adam()
train_teacher_student_gaussian_input(pruned_model, target_model, num_iter, bsize, optimizer)

Training loss at step 0: 68.9129
Training loss at step 200: 21.4804
Training loss at step 400: 10.5987
Training loss at step 600: 9.2376
Training loss at step 800: 8.7763
Training loss at step 1000: 8.5888
Training loss at step 1200: 8.6752
Training loss at step 1400: 9.1989
Training loss at step 1600: 8.6631
Training loss at step 1800: 8.5115
Training loss at step 2000: 9.4100
Training loss at step 2200: 8.9668
Training loss at step 2400: 7.6351
Training loss at step 2600: 8.9702
Training loss at step 2800: 8.5145


In [10]:
print(np.round(kernel_of_nn(pruned_model), 3))

[[ 1.    -0.241 -0.222 -0.242 -0.278]
 [-0.241  1.    -0.292 -0.212 -0.253]
 [-0.222 -0.292  1.    -0.284 -0.199]
 [-0.242 -0.212 -0.284  1.    -0.261]
 [-0.278 -0.253 -0.199 -0.261  1.   ]]


In [ ]:
print(np.round(kernel_of_nn(pruned_model, 1), 3))

[[ 1.     0.406  0.424  0.647  0.268]
 [ 0.406  1.     0.311  0.449 -0.017]
 [ 0.424  0.311  1.    -0.195  0.279]
 [ 0.647  0.449 -0.195  1.     0.411]
 [ 0.268 -0.017  0.279  0.411  1.   ]]


In [ ]:
# 4layers
d = 100
Ns = [1000, 100, 100]
Ms = [7, 5, 5]
out_dim = 1
num_iter = 20000
bsize = 5000

target_model = neural_net(d, Ns, out_dim)
pruned_model = neural_net(d, Ms, out_dim)
optimizer = tf.keras.optimizers.Adam()
train_teacher_student_gaussian_input(pruned_model, target_model, num_iter, bsize, optimizer)
print(np.round(kernel_of_nn(pruned_model), 2))

Training loss at step 0: 1.0515
Training loss at step 200: 0.3881
Training loss at step 400: 0.3250
Training loss at step 600: 0.3132
Training loss at step 800: 0.2898
Training loss at step 1000: 0.2744
Training loss at step 1200: 0.2737
Training loss at step 1400: 0.2581
Training loss at step 1600: 0.2571
Training loss at step 1800: 0.2525
Training loss at step 2000: 0.2566
Training loss at step 2200: 0.2530
Training loss at step 2400: 0.2741
Training loss at step 2600: 0.2606
Training loss at step 2800: 0.2628
Training loss at step 3000: 0.2638
Training loss at step 3200: 0.2558
Training loss at step 3400: 0.2492
Training loss at step 3600: 0.2588
Training loss at step 3800: 0.2491
Training loss at step 4000: 0.2461
Training loss at step 4200: 0.2480
Training loss at step 4400: 0.2463
Training loss at step 4600: 0.2527
Training loss at step 4800: 0.2511
Training loss at step 5000: 0.2483
Training loss at step 5200: 0.2606
Training loss at step 5400: 0.2480
Training loss at step 5600:

In [ ]:
# 4layers
d = 1000
Ns = [1000, 1000, 1000]
Ms = [7, 5, 5]
out_dim = 1
num_iter = 2000
bsize = 5000

target_model = neural_net(d, Ns, out_dim)
pruned_model = neural_net(d, Ms, out_dim)
optimizer = tf.keras.optimizers.Adam()
train_teacher_student_gaussian_input(pruned_model, target_model, num_iter, bsize, optimizer)
print(np.round(kernel_of_nn(pruned_model), 2))

Training loss at step 0: 33.4266
Training loss at step 200: 3.6897
Training loss at step 400: 3.3412
Training loss at step 600: 3.3787
Training loss at step 800: 3.3248
Training loss at step 1000: 3.1923
Training loss at step 1200: 3.3044
Training loss at step 1400: 3.3484
Training loss at step 1600: 3.3682
Training loss at step 1800: 3.2972
[[ 1.   -0.18 -0.14 -0.17 -0.14]
 [-0.18  1.   -0.15 -0.25 -0.12]
 [-0.14 -0.15  1.   -0.17 -0.2 ]
 [-0.17 -0.25 -0.17  1.   -0.14]
 [-0.14 -0.12 -0.2  -0.14  1.  ]]


In [23]:
from utils_tf import kernel_dist_from_etf
kernel_dist_from_etf(pruned_model)

0.00027871355786717177

## other losses 

In [52]:
from utils_tf import neural_net, kernel_of_nn, train_teacher_student_gaussian_input
from tensorflow.keras import backend as K
bce = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
# kld = tf.keras.losses.KLDivergence()
d = 500
Ns = [1000]
Ms = [5]
out_dim = 2
num_iter = 5000
bsize = 3000

target_model = neural_net(d, Ns, out_dim)
target_model.add(tf.keras.layers.Lambda(lambda x: K.cast(K.argmax(x, axis=-1), dtype='float32'), name='y_pred'))

pruned_model = neural_net(d, Ms, out_dim)

optimizer = tf.keras.optimizers.Adam()
train_teacher_student_gaussian_input(pruned_model, target_model, num_iter, bsize, optimizer, loss=bce)
print(np.round(kernel_of_nn(pruned_model), 2))
kernel_dist_from_etf(pruned_model)

Training loss at step 0: 0.6947
Training loss at step 200: 0.3735
Training loss at step 400: 0.3606
Training loss at step 600: 0.3563
Training loss at step 800: 0.3756
Training loss at step 1000: 0.3491
Training loss at step 1200: 0.3562
Training loss at step 1400: 0.3720
Training loss at step 1600: 0.3578
Training loss at step 1800: 0.3616
Training loss at step 2000: 0.3703
Training loss at step 2200: 0.3616
Training loss at step 2400: 0.3706
Training loss at step 2600: 0.3795
Training loss at step 2800: 0.3549
Training loss at step 3000: 0.3696
Training loss at step 3200: 0.3362
Training loss at step 3400: 0.3471
Training loss at step 3600: 0.3623
Training loss at step 3800: 0.3654
Training loss at step 4000: 0.3798
Training loss at step 4200: 0.3563
Training loss at step 4400: 0.3582
Training loss at step 4600: 0.3681
Training loss at step 4800: 0.3640
[[ 1.    0.58 -0.68 -0.67  0.42]
 [ 0.58  1.   -0.93 -0.93  0.57]
 [-0.68 -0.93  1.    0.87 -0.68]
 [-0.67 -0.93  0.87  1.   -0.69]


0.4708509290509846

In [56]:
# getting the accuracy
x = np.random.randn(bsize, d)
y_true = target_model(x).numpy()
y_pred = pruned_model(x).numpy()
print(y_true)
print(y_pred)
print(1 - np.mean(np.abs(y_true - np.argmax(y_pred, axis=-1))))

[1. 0. 1. ... 0. 1. 1.]
[[0.95272905 4.9233847 ]
 [2.0821726  0.8533565 ]
 [0.79050636 0.6494217 ]
 ...
 [3.997735   1.6128689 ]
 [2.6884027  2.671685  ]
 [2.8272302  1.1437169 ]]
0.8286666666666667


GD on cross entropy is not giving us the simplex

### what happens to the accuracy if the student model minimizes the L2 distance of logit probbailities rather than cross entropy? 

In [57]:
from utils_tf import neural_net, kernel_of_nn, train_teacher_student_gaussian_input
from tensorflow.keras import backend as K

d = 500
Ns = [1000]
Ms = [5]
out_dim = 2
num_iter = 5000
bsize = 3000

target_model = neural_net(d, Ns, out_dim)
# target_model.add(tf.keras.layers.Lambda(lambda x: K.cast(K.argmax(x, axis=-1), dtype='float32'), name='y_pred'))

pruned_model = neural_net(d, Ms, out_dim)

optimizer = tf.keras.optimizers.Adam()
train_teacher_student_gaussian_input(pruned_model, target_model, num_iter, bsize, optimizer)
print(np.round(kernel_of_nn(pruned_model), 2))
kernel_dist_from_etf(pruned_model)

Training loss at step 0: 127.9731
Training loss at step 200: 46.0856
Training loss at step 400: 20.8293
Training loss at step 600: 19.0541
Training loss at step 800: 19.2043
Training loss at step 1000: 18.6297
Training loss at step 1200: 18.3035
Training loss at step 1400: 18.7099
Training loss at step 1600: 18.6775
Training loss at step 1800: 19.2802
Training loss at step 2000: 18.8617
Training loss at step 2200: 18.6853
Training loss at step 2400: 18.4128
Training loss at step 2600: 18.5508
Training loss at step 2800: 18.4151
Training loss at step 3000: 18.6612
Training loss at step 3200: 19.4244
Training loss at step 3400: 19.2275
Training loss at step 3600: 18.7003
Training loss at step 3800: 18.2228
Training loss at step 4000: 19.2812
Training loss at step 4200: 19.0678
Training loss at step 4400: 18.3825
Training loss at step 4600: 18.1551
Training loss at step 4800: 19.0573
[[ 1.   -0.25 -0.25 -0.25 -0.25]
 [-0.25  1.   -0.25 -0.25 -0.25]
 [-0.25 -0.25  1.   -0.25 -0.25]
 [-0.25

5.337726472420812e-06

In [58]:
# getting the accuracy
x = np.random.randn(bsize, d)
y_true = np.argmax(target_model(x).numpy(), axis=-1)
y_pred = np.argmax(pruned_model(x).numpy(), axis=-1)
print(y_true)
print(y_pred)
print(1 - np.mean(np.abs(y_true - y_pred)))

[0 0 0 ... 0 0 1]
[1 0 1 ... 1 0 0]
0.521


In [60]:
x = np.random.randn(bsize, d)
print(target_model(x).numpy())
print(pruned_model(x).numpy())

[[12.396739 13.208958]
 [11.581356 10.946937]
 [12.304425 12.698814]
 ...
 [13.062091 13.319418]
 [11.864744 12.299384]
 [12.530563 12.408303]]
[[19.202206  19.197853 ]
 [11.625981  11.597779 ]
 [ 9.620443   9.609297 ]
 ...
 [12.545544  12.538453 ]
 [ 7.8893394  7.8705926]
 [10.828065  10.868833 ]]


why are the output of the pruned net the same :/

# pruning a two-layer net trained on mnist

In [3]:
from utils_tf import load_mnist_evod
x_train, y_train, x_test, y_test = load_mnist_evod()

11501568/11490434 [==============================] - 1s 0us/step


In [5]:
x_train.shape

(60000, 784)

In [6]:
from utils_tf import neural_net, kernel_of_nn, train_teacher_student_gaussian_input
from tensorflow.keras import backend as K
bce = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
d = 784
Ns = [1000]
Ms = [5]
out_dim = 2
num_iter = 5000
bsize = 3000

target_model = neural_net(d, Ns, out_dim)
target_model.compile(optimizer=tf.keras.optimizers.Adam(),
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),)

target_model.fit(
    x_train, y_train, batch_size=bsize,
    epochs=20,
    validation_data=(x_test, y_test),
)



Epoch 1/20
20/20 [==============================] - 3s 25ms/step - loss: 0.4791 - val_loss: 0.3041
Epoch 2/20
20/20 [==============================] - 0s 12ms/step - loss: 0.2297 - val_loss: 0.2130
Epoch 3/20
20/20 [==============================] - 0s 11ms/step - loss: 0.1548 - val_loss: 0.1790
Epoch 4/20
20/20 [==============================] - 0s 12ms/step - loss: 0.1080 - val_loss: 0.1584
Epoch 5/20
20/20 [==============================] - 0s 11ms/step - loss: 0.0728 - val_loss: 0.1395
Epoch 6/20
20/20 [==============================] - 0s 10ms/step - loss: 0.0486 - val_loss: 0.1290
Epoch 7/20
20/20 [==============================] - 0s 11ms/step - loss: 0.0325 - val_loss: 0.1248
Epoch 8/20
20/20 [==============================] - 0s 10ms/step - loss: 0.0224 - val_loss: 0.1218
Epoch 9/20
20/20 [==============================] - 0s 10ms/step - loss: 0.0163 - val_loss: 0.1229
Epoch 10/20
20/20 [==============================] - 0s 10ms/step - loss: 0.0118 - val_loss: 0.1218
Epoch 11/

In [10]:
def pred(model):
  return np.argmax(model(x_test), axis=-1)

def ret_acc(model):
  # print("test_accuracy = ", np.mean(y_test_evod * 1.0 == np.ndarray.flatten((1 + np.sign(model(x_test)))/2)))
  return( np.mean(y_test * 1.0 == pred(model)))

def ret_mse(model, x_test):
  # Using 'auto'/'sum_over_batch_size' reduction type.
  mse = tf.keras.losses.MeanSquaredError()
  return(mse(y_test * 1.0, pred(model, x_test)).numpy())

ret_acc(target_model)

0.9662

In [13]:
pruned_model = neural_net(d, Ms, out_dim)

optimizer = tf.keras.optimizers.Adam()
train_teacher_student_gaussian_input(pruned_model, target_model, num_iter, bsize, optimizer)
print(np.round(kernel_of_nn(pruned_model), 2))


Training loss at step 0: 195.6691
Training loss at step 200: 83.9421
Training loss at step 400: 41.6644
Training loss at step 600: 37.0372
Training loss at step 800: 35.1259
Training loss at step 1000: 34.2629
Training loss at step 1200: 33.3891
Training loss at step 1400: 32.2989
Training loss at step 1600: 31.1541
Training loss at step 1800: 30.3966
Training loss at step 2000: 29.6119
Training loss at step 2200: 29.4550
Training loss at step 2400: 28.6847
Training loss at step 2600: 27.9415
Training loss at step 2800: 27.9100
Training loss at step 3000: 28.0031
Training loss at step 3200: 29.5676
Training loss at step 3400: 28.3626
Training loss at step 3600: 28.6376
Training loss at step 3800: 27.2555
Training loss at step 4000: 27.4899
Training loss at step 4200: 28.5962
Training loss at step 4400: 28.2936
Training loss at step 4600: 28.7095
Training loss at step 4800: 28.0914
[[ 1.   -0.27 -0.28 -0.25 -0.17]
 [-0.27  1.   -0.16 -0.24 -0.29]
 [-0.28 -0.16  1.   -0.23 -0.32]
 [-0.25

NameError: ignored

In [ ]:
# multiclass mnist pruning


In [59]:
# logging and saving